{% set version = "0.2.1" %}

package:
  name: locket
  version: {{ version }}

source:
  fn: locket-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/l/locket/locket-{{ version }}.tar.gz
  md5: b5e4e9dea58264f636f7044c867e2c6d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - locket

about:
  home: https://github.com/mwilliamson/locket.py
  license: BSD 2-Clause
  license_file: LICENSE
  summary: File-based locks for Python for Linux and Windows

extra:
  recipe-maintainers:
    - jcrist
