travis:
  secure:
    BINSTAR_TOKEN: pbSHVcBTomNxJ9mTn/qldRiTJLV5xOnF3iAb5YhLIOGRT8A/ej2XzMftMvZLW2NBTH9K5dcbzSuc9uN5Ef+guul4i0oUFYTkRUvmbSdY9ouIAOdKEVr1r1cIut7IPf/TycagnPFTG/4ba8pQdBmTVv7GjROBPwKKEZ2mLA69GJFllnrMvIh0Qrxlp6M1tNuunPn3RV17jcZfTlZXuoUriWo0IIO3msUeM7rbOZF9lrjVpYBcs5yuBO0Z5vbiV4EIoq9L9IODLeTQyu4ho061ZMZNCAdXFYpJ7kTH8TFNwzRjglr9JihVIolWd1+3SxiKmgCi3GsVytvN2F6VQbctXnRLaB3bqHnDT+YaKWTbuG/wSnq42Z5f1z0CZ8+p3SI4MywlIo5ixjDFZijNBHI0XLpArIv/lWhUxQAUpq6YoZsBq6WlcU36dhU4DR/qEzR/rIWMnlx/avlWOPGJw98APS6lC4aB42Kua6S+/hz0zq7PLIttt4xUcVzq3gwBj9hp1WoUoFDF4xBp9UZAS6N+tI4qkFz/Re31aXxohmkhnCvGcJoUyU0nt4c+l6nP6MGWU2YWwgjxPvZ3qoRsGKOjmCH1dvmAZcY5g8TCRBPkg92Ut62ThJTapt48gAtiABZ+wDc2oorbeqh5S6SQMxiRzNhVk6FBs83Dos2sG2WW47U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
