travis:
  secure:
    BINSTAR_TOKEN: S+11dvotlHIEhVeG2jy3MloNgi1K1ZZ6zFhRK9d4wuTNbLF4VMX/OwelW3JbqMhmyWQwmvT4kXrhhhX0WRNEl8nWF2DhDCX3SUQ9FSkL3+sXfWOEtsERUFGRSFbmhHVXFyPmkmV1LW2IsTN20uIizWfYpb5h6PlMPuKNC9CjB+T5UC9x8DHDlZ/JE/udOAzSqBGTOK2hd29C0LoBfk5KA7wJm4jjdUMZ3dkCofYXD2JEC5j2BHlEFe5q7Co3zin6fSVvjM529DexzLZvjDeD5rNkHMS0IYroyrp271gVceQjPN4McHocNkaEZrT32CzZdkTVdTdU+isPSV6CSyqNRgat5PfyHpaLbS97V+pUrTJS7IakJ6FwYkA14uJQo097GPLZketv8kiP6C814ygdkybXJ9JJNYpFwBkGeZLK0RL1rK+vyjNjZvtJFbcJ/IndF40lm8oOvaH6seVhqydKN6Wq2aiQoR80PqkUhpkF+GjxerGbkYCcQ3hLLhrIuA3973dyE3LFa++gXET4bPvea6/RUtU0atVNYZjp8kyzJkEM0FX0V057WVluJn1JGjda1dKWPff+8dTTnwKMq/VJpCesE0hQAnfb+7wSw9DccbvslH8QOCTPRs8/vJ6USTyBXOguQfOyaTWY3G0MTZdvKQAipxs20pNw//MXDGA6OP4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
